apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce-lab
type: Opaque
stringData:
  POSTGRES_DB: ecommerce
  POSTGRES_USER: ecommerce
  POSTGRES_PASSWORD: ecommerce123
  DATABASE_URL: postgresql://ecommerce:ecommerce123@postgres:5432/ecommerce
